imports:
    - { resource: stopwords.yml }

parameters:
    cache.backend.options:
        dir: %cache.path%
        file_extension: .cache
        
    cache.path: %classifier_path%/cache

    svm.class: SVM
    svm.options:
      %svm.kernel_type%: %svm.kernel_type.linear%

    svm.kernel_type: 102
    svm.kernel_type.linear: 0

    classifier_namespace: Camspiers\StatisticalClassifier

    tokenizer.word.class: %classifier_namespace%\Tokenizer\Word
    normalizer.lowercase.class: %classifier_namespace%\Normalizer\Lowercase
    normalizer.porter.class: %classifier_namespace%\Normalizer\Porter
    normalizer.stopword.class: %classifier_namespace%\Normalizer\Stopword
    normalizer.grouped.class: %classifier_namespace%\Normalizer\Grouped
    converter.converter.class: %classifier_namespace%\DataSource\Converter
    classifier.complement_naive_bayes.class: %classifier_namespace%\Classifier\ComplementNaiveBayes
    classifier.svm.class: %classifier_namespace%\Classifier\SVM
    console.application.class: %classifier_namespace%\Console\Application
    console.application.name: PHP Classifier
    console.application.version: ~package_version~
    console.command.model.remove.class: %classifier_namespace%\Console\Command\Model\RemoveCommand
    console.command.model.prepare.class: %classifier_namespace%\Console\Command\Model\PrepareCommand
    console.command.train.document.class: %classifier_namespace%\Console\Command\Train\DocumentCommand
    console.command.train.directory.class: %classifier_namespace%\Console\Command\Train\DirectoryCommand
    console.command.train.pdo.class: %classifier_namespace%\Console\Command\Train\PDOCommand
    console.command.classify.class: %classifier_namespace%\Console\Command\ClassifyCommand
    console.command.test.pdo.class: %classifier_namespace%\Console\Command\Test\PDOCommand
    console.command.test.directory.class: %classifier_namespace%\Console\Command\Test\DirectoryCommand
    console.command.server.run.class: %classifier_namespace%\Console\Command\Server\RunCommand
    console.command.generate_container.class: %classifier_namespace%\Console\Command\GenerateContainerCommand
    console.command.config.create.class: %classifier_namespace%\Console\Command\Config\CreateCommand
    console.command.config.remove.class: %classifier_namespace%\Console\Command\Config\RemoveCommand
    console.command.config.open.class: %classifier_namespace%\Console\Command\Config\OpenCommand
    console.command.self_update.class: %classifier_namespace%\Console\Command\SelfUpdateCommand

    cache.class: CacheCache\Cache
    cache.backend.class: CacheCache\Backends\File

    json_pretty.class: Camspiers\JsonPretty\JsonPretty

services:
    # Tokenizers
    tokenizer.word:
        class: %tokenizer.word.class%

    # Normalizers
    normalizer.lowercase:
        class: %normalizer.lowercase.class%
    normalizer.porter:
        class: %normalizer.porter.class%
    normalizer.stopword:
        class: %normalizer.stopword.class%
        arguments:
            - %stopwords%
    normalizer.stopword_lowercase:
        class: %normalizer.grouped.class%
        arguments:
            - [ @normalizer.lowercase, @normalizer.stopword ]
    normalizer.stopword_lowercase_porter:
        class: %normalizer.grouped.class%
        arguments:
            - [ @normalizer.stopword_lowercase, @normalizer.porter  ]

    # Converter
    converter.converter:
        class: %converter.converter.class%
        arguments:
            - @converter.from
            - @converter.to

    converter.from:
        synthetic: true
    converter.to:
        synthetic: true

    # Classifiers
    classifier.complement_naive_bayes:
        class: %classifier.complement_naive_bayes.class%
        arguments:
            - @classifier.source
            - @classifier.model
            - @tokenizer.word
            - @normalizer.stopword_lowercase

    classifier.svm:
        class: %classifier.svm.class%
        arguments:
            - @classifier.source
            - @classifier.model
            - @tokenizer.word
            - @normalizer.stopword_lowercase
            - @svm

    # SVM
    svm:
      class: %svm.class%
      calls:
        - [ setOptions, [ %svm.options% ] ]

    # model
    classifier.model:
        synthetic: true
        
    # source
    classifier.source:
        synthetic: true

    # Caches
    cache:
        class: %cache.class%
        arguments:
            - @cache.backend

    cache.backend:
        class: %cache.backend.class%
        arguments:
            - %cache.backend.options%

    # Console
    console.application:
        class: %console.application.class%
        arguments:
          - %console.application.name%
          - %console.application.version%

    console.command.model.remove:
        class: %console.command.model.remove.class%
        tags:
            - { name: console.command, cache: true }

    console.command.model.prepare:
        class: %console.command.model.prepare.class%
        tags:
            - { name: console.command, cache: true }

    console.command.train.document:
        class: %console.command.train.document.class%
        tags:
            - { name: console.command, cache: true }

    console.command.train.directory:
        class: %console.command.train.directory.class%
        tags:
            - { name: console.command, cache: true }

    console.command.train.pdo:
        class: %console.command.train.pdo.class%
        tags:
            - { name: console.command, cache: true }

    console.command.classify:
        class: %console.command.classify.class%
        tags:
            - { name: console.command, cache: true }

    console.command.test.pdo:
        class: %console.command.test.pdo.class%
        tags:
            - { name: console.command, cache: true }

    console.command.test.directory:
        class: %console.command.test.directory.class%
        tags:
            - { name: console.command, cache: true }

    console.command.server.run:
        class: %console.command.server.run.class%
        tags:
            - { name: console.command, cache: true }

    console.command.config.create:
        class: %console.command.config.create.class%
        arguments: [ @json_pretty ]
        tags:
            - { name: console.command }

    console.command.config.remove:
        class: %console.command.config.remove.class%
        tags:
            - { name: console.command }

    console.command.config.open:
        class: %console.command.config.open.class%
        tags:
            - { name: console.command }

    console.command.generate_container:
        class: %console.command.generate_container.class%
        tags:
            - { name: console.command }

    console.command.self_update:
        class: %console.command.self_update.class%
        tags:
            - { name: console.command }

    json_pretty:
        class: %json_pretty.class%
